# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: cc8b3de
_src_path: git@github.com:MeteoSwiss-APN/mch-python-blueprint.git
email: simon.adamov@meteoswiss.ch
full_name: Simon Adamov
github_username: MeteoSwiss
module_name: weathergraphnet
project_doc_url: https://github.io/MeteoSwiss/weathergraphnet
project_github: https://github.com/MeteoSwiss/weathergraphnet
project_keywords: WeatherGraphNet, GNN, DeepLearning, Ensembles, ICON, WeatherML
project_name: WeatherGraphNet
project_short_description: Simon Adamov's WeatherGraphNet to Generate Weather Model
    Ensemble Members
project_slug: weathergraphnet
project_ssh_url: git+ssh://git@github.com/MeteoSwiss/weathergraphnet.git
python_version: '3.10'
version: 0.1.0
year: '2023'
