# Standard library
from typing import Any

# Third-party
from _typeshed import Incomplete

config: Incomplete

def input_file() -> str: ...
def var_name(): ...
def member_name(): ...
def var(input_file: Any, var_name: str = ...): ...
def fig(): ...
def ax(fig): ...
def im(ax: Any, var: Any): ...
def test_get_member_name(input_file: Any, member_name: str = ...): ...
def test_create_update_function(
    im: Any, var: Any, member_name: str = ..., var_name: str = ...
): ...
def test_create_animation_object(fig, var, im, member_name, var_name) -> None: ...
def test_save_animation(tmp_path, im, var, member_name, var_name, fig) -> None: ...
def test_main(tmp_path, input_file, var_name) -> None: ...
