name: weathergraphnet
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
  - r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.13
  - alembic=1.11.1
  - alsa-lib=1.2.9
  - anaconda-client=1.12.0
  - anaconda-project=0.11.1
  - anyio=3.7.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - asciitree=0.3.3
  - astroid=2.15.6
  - asttokens=2.2.1
  - async-lru=2.0.4
  - attr=2.5.1
  - attrs=23.1.0
  - aws-c-auth=0.7.0
  - aws-c-cal=0.6.0
  - aws-c-common=0.8.23
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.1
  - aws-c-http=0.7.11
  - aws-c-io=0.13.28
  - aws-c-mqtt=0.8.14
  - aws-c-s3=0.3.13
  - aws-c-sdkutils=0.1.11
  - aws-checksums=0.1.16
  - aws-crt-cpp=0.20.3
  - aws-sdk-cpp=1.10.57
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bcrypt=3.2.2
  - beautifulsoup4=4.12.2
  - black=23.7.0
  - bleach=6.0.0
  - blinker=1.6.2
  - boa=0.15.1
  - bokeh=3.2.1
  - boltons=23.0.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfgv=3.3.1
  - chardet=5.1.0
  - charset-normalizer=3.2.0
  - click=8.1.6
  - cloudpickle=2.2.1
  - clyent=1.2.2
  - codespell=2.2.5
  - colorama=0.4.6
  - comm=0.1.3
  - conda=23.3.1
  - conda-build=3.25.0
  - conda-index=0.2.3
  - conda-pack=0.7.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.8.0
  - configparser=5.3.0
  - contourpy=1.1.0
  - cryptography=41.0.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cudatoolkit=11.8.0
  - cycler=0.11.0
  - cytoolz=0.12.2
  - dask=2023.7.1
  - dask-core=2023.7.1
  - dask-glm=0.2.0
  - dask-ml=2023.3.24
  - databricks-cli=0.17.7
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.7
  - distlib=0.3.7
  - distributed=2023.7.1
  - docker-py=6.1.3
  - entrypoints=0.4
  - exceptiongroup=1.1.2
  - executing=1.2.0
  - expat=2.5.0
  - fasteners=0.17.3
  - filelock=3.12.2
  - flake8=6.0.0
  - flake8-black=0.3.6
  - flask=2.3.2
  - flit-core=3.9.0
  - fmt=9.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.41.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - fsspec=2023.6.0
  - gettext=0.21.1
  - gflags=2.2.2
  - gitdb=4.0.10
  - gitpython=3.1.32
  - glib=2.76.4
  - glib-tools=2.76.4
  - glob2=0.7
  - glog=0.6.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - graphite2=1.3.13
  - greenlet=2.0.2
  - gst-plugins-base=1.22.5
  - gstreamer=1.22.5
  - gunicorn=20.1.0
  - harfbuzz=7.3.0
  - icu=72.1
  - identify=2.5.26
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=4.13.0
  - importlib_metadata=4.13.0
  - importlib_resources=6.0.0
  - iniconfig=2.0.0
  - ipdb=0.13.13
  - ipykernel=6.25.0
  - ipython=8.14.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.7
  - isoduration=20.11.0
  - isort=5.12.0
  - itsdangerous=2.1.2
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.3.0
  - json5=0.9.14
  - jsonpatch=1.32
  - jsonpointer=2.0
  - jsonschema=4.18.4
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.18.4
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.1
  - jupyter_events=0.6.3
  - jupyter_server=2.7.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.24.0
  - jupyterlab_widgets=3.0.8
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.21.1
  - lame=3.100
  - lazy-object-proxy=1.9.0
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.3
  - libarchive=3.6.2
  - libarrow=12.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.69
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.7.0.149
  - libcups=2.3.3
  - libcurand=10.3.3.53
  - libcurl=8.2.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.1.0
  - libgcrypt=1.10.1
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.4
  - libgomp=13.1.0
  - libgoogle-cloud=2.12.0
  - libgpg-error=1.47
  - libgrpc=1.54.2
  - libhwloc=2.9.2
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblief=0.12.3
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libmamba=1.4.2
  - libmambapy=1.4.2
  - libnghttp2=1.52.0
  - libnpp=11.8.0.86
  - libnsl=2.0.0
  - libnuma=2.0.16
  - libnvjpeg=11.9.0.86
  - libogg=1.3.4
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libsystemd0=254
  - libthrift=0.18.1
  - libtiff=4.5.1
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libxkbcommon=1.5.0
  - libxml2=2.11.4
  - libzlib=1.2.13
  - lightning-utilities=0.9.0
  - livereload=2.6.3
  - llvm-openmp=16.0.6
  - llvmlite=0.40.1
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - lzo=2.10
  - mako=1.2.4
  - mamba=1.4.2
  - markdown=3.4.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mkl=2022.2.1
  - mlflow=2.5.0
  - more-itertools=10.0.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpg123=1.31.3
  - mpmath=1.3.0
  - msgpack-python=1.0.5
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy=1.4.1
  - mypy_extensions=1.0.0
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nbclient=0.8.0
  - nbconvert=7.7.3
  - nbconvert-core=7.7.3
  - nbconvert-pandoc=7.7.3
  - nbformat=5.9.1
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - nodeenv=1.8.0
  - notebook=7.0.0
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89
  - numba=0.57.1
  - numcodecs=0.11.0
  - numpy=1.24.4
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.1.1
  - orc=1.9.0
  - overrides=7.3.1
  - packaging=23.1
  - pandas=2.0.3
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - paramiko=3.3.1
  - parso=0.8.3
  - partd=1.4.0
  - patch=2.7.6
  - patchelf=0.17.2
  - pathspec=0.11.2
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.0
  - pip=23.2.1
  - pixman=0.40.0
  - pkginfo=1.9.6
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.9.1
  - pluggy=1.2.0
  - ply=3.11
  - pooch=1.7.0
  - pre-commit=3.3.3
  - prometheus_client=0.17.1
  - prometheus_flask_exporter=0.22.4
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - protobuf=4.21.12
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - py-lief=0.12.3
  - pyarrow=12.0.1
  - pybind11-abi=4
  - pycodestyle=2.10.0
  - pycosat=0.6.4
  - pycparser=2.21
  - pydantic=1.10.12
  - pydocstyle=6.3.0
  - pyflakes=3.0.1
  - pygments=2.15.1
  - pyjwt=2.8.0
  - pylint=2.17.5
  - pynacl=1.5.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyprojroot=0.3.0
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - pytest=7.4.0
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-json-logger=2.0.7
  - python-libarchive-c=5.0
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytoolconfig=1.2.5
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-lightning=2.0.6
  - pytz=2023.3
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qt-main=5.15.8
  - qtconsole=5.4.3
  - qtconsole-base=5.4.3
  - qtpy=2.3.1
  - querystring_parser=1.2.4
  - rdma-core=28.9
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.30.0
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.5.0
  - ripgrep=13.0.0
  - rocm-smi=5.6.0
  - rope=1.9.0
  - rpds-py=0.9.2
  - rstcheck=6.1.2
  - rstcheck-core=1.0.3
  - ruamel.yaml=0.17.32
  - ruamel.yaml.clib=0.2.7
  - ruamel_yaml=0.15.80
  - s2n=1.3.46
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - send2trash=1.8.2
  - setuptools=68.0.0
  - shellingham=1.5.1
  - sip=6.7.10
  - six=1.16.0
  - sleef=3.5.1
  - smmap=3.0.5
  - snappy=1.1.10
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sphinx=7.1.1
  - sphinx-autobuild=2021.3.14
  - sphinxcontrib-applehelp=1.0.4
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlalchemy=2.0.19
  - sqlparse=0.4.4
  - stack_data=0.6.2
  - sympy=1.12
  - tabulate=0.9.0
  - tbb=2021.10.0
  - tblib=1.7.0
  - terminado=0.17.1
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.12.1
  - toolz=0.12.0
  - torchmetrics=0.11.4
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typer=0.4.2
  - types-docutils=0.18.3
  - types-setuptools=68.0.0.3
  - types-toml=0.10.8.7
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typing_utils=0.1.0
  - tzdata=2023c
  - ucx=1.14.1
  - ukkonen=1.0.1
  - uri-template=1.3.0
  - urllib3=1.26.15
  - virtualenv=20.24.2
  - watchgod=0.8.2
  - wcwidth=0.2.6
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.1
  - werkzeug=2.3.6
  - wheel=0.41.0
  - widgetsnbextension=4.0.8
  - wrapt=1.15.0
  - xarray=2023.7.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.39
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xyzservices=2023.7.0
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zarr=2.16.0
  - zeromq=4.3.4
  - zict=3.0.0
  - zipp=3.16.2
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - appdirs==1.4.4
      - cattrs==23.1.2
      - copier==8.1.0
      - doc8==1.1.1
      - docutils==0.20.1
      - dunamai==1.18.0
      - esbonio==0.16.1
      - flake8-pyproject==1.2.3
      - funcy==2.0
      - jinja2-ansible-filters==1.3.2
      - lsprotocol==2023.0.0a2
      - mistune==2.0.5
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.18.3
      - nvidia-nvtx-cu11==11.8.86
      - pbr==5.11.1
      - plumbum==1.8.2
      - pygls==1.0.2
      - pyspellchecker==0.7.2
      - pyyaml-include==1.3.1
      - questionary==1.10.0
      - restructuredtext-lint==1.4.0
      - sphinx-mdinclude==0.5.3
      - stevedore==5.1.0
      - torch-geometric==2.3.1
      - typeguard==3.0.2
