name: weathergraphnet
channels:
  - conda-forge
  - defaults
  - r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.13
  - anaconda-client=1.11.3
  - anaconda-project=0.11.1
  - anyio=3.7.0
  - astroid=2.15.5
  - asttokens=2.2.1
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - black=23.3.0
  - boa=0.14.0
  - boltons=23.0.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - cfgv=3.3.1
  - chardet=5.1.0
  - charset-normalizer=3.1.0
  - click=8.1.3
  - clyent=1.2.2
  - codespell=2.2.5
  - colorama=0.4.6
  - conda=23.3.1
  - conda-build=3.24.0
  - conda-pack=0.7.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.8.0
  - cryptography=41.0.1
  - dataclasses=0.8
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.6
  - distlib=0.3.6
  - docutils=0.18.1
  - exceptiongroup=1.1.1
  - executing=1.2.0
  - filelock=3.12.2
  - flake8=6.0.0
  - flake8-black=0.3.6
  - fmt=9.1.0
  - freetype=2.12.1
  - glob2=0.7
  - icu=72.1
  - identify=2.5.24
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=4.13.0
  - importlib_resources=5.12.0
  - iniconfig=2.0.0
  - ipdb=0.13.13
  - ipython=8.14.0
  - isort=5.12.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - json5=0.9.5
  - jsonpatch=1.32
  - jsonpointer=2.0
  - jsonschema=4.17.3
  - jupyter_core=5.3.1
  - keyutils=1.6.1
  - krb5=1.20.1
  - lazy-object-proxy=1.9.0
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libarchive=3.6.2
  - libcurl=8.1.2
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgomp=13.1.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblief=0.12.3
  - libmamba=1.4.2
  - libmambapy=1.4.2
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libpng=1.6.39
  - libsolv=0.7.24
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxml2=2.11.4
  - libzlib=1.2.13
  - livereload=2.6.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.4.2
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mypy=1.3.0
  - mypy_extensions=1.0.0
  - nbformat=5.9.0
  - ncurses=6.4
  - nodeenv=1.8.0
  - openjpeg=2.5.0
  - openssl=3.1.1
  - packaging=23.1
  - parso=0.8.3
  - patch=2.7.6
  - patchelf=0.18.0
  - pathspec=0.11.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.5.0
  - pip=23.1.2
  - pkginfo=1.9.6
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.5.3
  - pluggy=1.0.0
  - pre-commit=3.3.3
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-lief=0.12.3
  - pybind11-abi=4
  - pycodestyle=2.10.0
  - pycosat=0.6.4
  - pycparser=2.21
  - pydantic=1.10.9
  - pydocstyle=6.3.0
  - pyflakes=3.0.1
  - pygments=2.15.1
  - pylint=2.17.4
  - pyopenssl=23.2.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - pytest=7.3.2
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.17.1
  - python-libarchive-c=4.0
  - python_abi=3.11
  - pytoolconfig=1.2.5
  - pytz=2023.3
  - pyyaml=6.0
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - requests-toolbelt=1.0.0
  - rich=13.4.2
  - ripgrep=13.0.0
  - rope=1.8.0
  - rstcheck=6.1.2
  - rstcheck-core=1.0.3
  - ruamel.yaml=0.17.31
  - ruamel.yaml.clib=0.2.7
  - ruamel_yaml=0.15.80
  - setuptools=67.7.2
  - shellingham=1.5.1
  - six=1.16.0
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - soupsieve=2.3.2.post1
  - sphinx=7.0.1
  - sphinx-autobuild=2021.3.14
  - sphinxcontrib-applehelp=1.0.4
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - stack_data=0.6.2
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.8
  - toolz=0.12.0
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typer=0.4.2
  - types-docutils=0.18.3
  - types-setuptools=67.8.0.0
  - types-toml=0.10.8.6
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - ukkonen=1.0.1
  - urllib3=1.26.15
  - virtualenv=20.23.0
  - watchgod=0.8.2
  - wcwidth=0.2.6
  - wheel=0.40.0
  - wrapt=1.15.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zipp=3.15.0
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - copier==8.0.0
      - dunamai==1.17.0
      - flake8-pyproject==1.2.3
      - funcy==2.0
      - jinja2-ansible-filters==1.3.2
      - mistune==2.0.5
      - plumbum==1.8.2
      - pyyaml-include==1.3
      - questionary==1.10.0
      - sphinx-mdinclude==0.5.3
